# -*- coding: utf-8 -*-
"""DataScience_Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQ0dK-knBdwLWE9pbeYyVCiyK8g64X5F

1) After running the following code, what does the variable bacon contain?

bacon = 22

bacon + 1

bacon = 23
"""

bacon = 22
bacon += 1
print(bacon)

"""2) What should the values of the following two terms be?

'spam' + 'spamspam' = 'spamspamspam'

'spam' * 3 = 'spamspamspam'

"""

print("spam" + "spamspam")
print("spam" * 3)

"""3) How can you tell the difference between break and continue?

If the loop exits then its break that's being used and if the loop skips then its continue that's being used.

4) In a for loop, what is the difference between range(10), range(0, 10), and range(0, 10, 1)?

Actually, there is no difference. Range can take 3 values (x, y, z)
in which if either of x and y or both is not defined then it takes default value, i.e, x=0, z=1 in which x is the starting index and z is the index updation.

5) Using a for loop, write a short programme that prints the numbers 1 to 10 Then, using a while loop, create an identical programme that prints the numbers 1 to 10.
"""

for i in range(1,11):
  print(i)

i = 1
while i < 11:
  print(i)
  i += 1

"""6) Given a number x, determine whether the given number is Armstrong number or not.

Input : 153

Output : Yes

153 is an Armstrong number.

1 * 1 * 1 + 5 * 5 * 5 + 3 * 3 * 3 = 153
"""

armstrong = input("Enter the number : ")

x = 0
for i in armstrong:
  i = int(i)
  x += i ** 3

if x == int(armstrong):print("The number is armstrong")
else:print("The number is not armstrong")

"""7) Program to find Sum of squares of first n natural numbers.

"""

n = int(input("Enter the natural number n: "))

sum_squares = 0
for i in range(1, n+1):
  sum_squares += i ** 2

print(sum_squares)

"""8) Program to Reverse words in a given String in Python."""

string = input("Enter the string to be reversed: ")

reverse=string[::-1]

print(reverse)

"""9) Given a list of numbers, write a Python program to find the sum of all the elements in the list.

Input: [10,12,13]

Output: 35
"""

li = [int(i) for i in input("Enter the numbers seperated by space :").split()]

sum = 0
for i in li:
  sum += i

print(sum)

"""10) Write a Python program to print all even numbers between 10-1000."""

for i in range (10, 1001, 2):
  print(i)